/**
 * JVTO WhatsApp template pack.
 *
 * Source material:
 * - Google Doc: Comprehensive Customer Portal FAQ
 * - Document ID: 1aS268d31sM2xYeNqoGwbdu3iuOQvkFv5_zesw0OkA54
 * - Last confirmed modified time: 2026-05-19T13:49:31.551Z
 */

export type JvtoTemplateVariable = {
  name: string;
  isRequired: boolean;
  description: string;
  example: string;
};

export type JvtoTemplateDefinition = {
  name: string;
  description: string;
  content: string;
  mediaType: "image" | "file" | "video" | null;
  mediaUrl: string | null;
  mediaFilename: string | null;
  variables: JvtoTemplateVariable[];
};

const portalUrl = {
  name: "portal_url",
  isRequired: true,
  description: "Full customer portal URL for this booking or trip",
  example: "https://javavolcano-touroperator.com/my-trips/cus_abc123",
};

const customerName = {
  name: "customer_name",
  isRequired: true,
  description: "Customer or lead guest name",
  example: "John Doe",
};

const packageName = {
  name: "package_name",
  isRequired: true,
  description: "Booked tour package name",
  example: "3D2N Mount Bromo & Ijen Crater Tour",
};

export const jvtoTemplatePack: JvtoTemplateDefinition[] = [
  {
    name: "JVTO Pre-Trip Prep Checklist",
    description: "Early preparation checklist for packing, health, cash, waterproof gear, and portal review.",
    content: [
      "*[JVTO] Pre-Trip Preparation Checklist*",
      "",
      "Hi {customer_name}, your *{package_name}* starts on *{trip_start_date}*.",
      "",
      "Please prepare these essentials before your trip:",
      "- Warm layers for Bromo/Ijen sunrise and night temperatures",
      "- Sturdy trekking shoes or hiking boots with good grip",
      "- Quick-dry clothes, poncho, and waterproof bag for waterfall routes",
      "- Personal medication, sunscreen, insect repellent, and basic first aid",
      "- Headlamp or flashlight for night trekking",
      "- Local cash in IDR for personal expenses, tips, and optional add-ons",
      "- Camera/electronics protection, especially for sulfur and waterfall areas",
      "",
      "Your detailed itinerary, inclusions, payment history, and trip tips are here:",
      "{portal_url}",
      "",
      "Please review it before departure so the team can resolve questions early.",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      packageName,
      {
        name: "trip_start_date",
        isRequired: true,
        description: "First day of the customer's tour",
        example: "15 Jan 2026",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO Ijen Medical & Passport Requirements",
    description: "Ijen-specific reminder for medical check-up, passport copy, permit readiness, and respiratory caution.",
    content: [
      "*[JVTO] Ijen Medical & Passport Requirements*",
      "",
      "Hi {customer_name}, for your Ijen trek on *{ijen_date}*, please prepare these mandatory items:",
      "",
      "*1. Medical check-up*",
      "- Location: {medical_check_location}",
      "- Time: {medical_check_time}",
      "- Cost: IDR 35,000 per person",
      "- Purpose: to confirm good physical and mental condition before the trek",
      "",
      "*2. Printed passport copy*",
      "- Please prepare a clear printed passport copy for Ijen permit processing and registration.",
      "",
      "*Health note*",
      "Ijen Crater is not suitable for guests with asthma or severe respiratory issues because of sulfur fumes. JVTO provides a gas mask, but a personal mask is also advisable if you prefer your own fit.",
      "",
      "Full trip details:",
      "{portal_url}",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      {
        name: "ijen_date",
        isRequired: true,
        description: "Date of the customer's Ijen trek",
        example: "16 Jan 2026",
      },
      {
        name: "medical_check_location",
        isRequired: true,
        description: "Where the medical check-up will be conducted",
        example: "Hotel lobby",
      },
      {
        name: "medical_check_time",
        isRequired: true,
        description: "Scheduled medical check-up time",
        example: "20:00",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO Pickup Logistics Confirmation",
    description: "Confirms pickup date, time, pickup point, drop-off point, and portal reference.",
    content: [
      "*[JVTO] Pickup Logistics Confirmation*",
      "",
      "Hi {customer_name}, here are your confirmed pickup details:",
      "",
      "- *Date:* {pickup_date}",
      "- *Pickup time:* {pickup_time}",
      "- *Pickup location:* {pickup_location}",
      "- *Drop-off location:* {dropoff_location}",
      "",
      "Please be ready at the pickup point a few minutes before the scheduled time. If you are arriving by flight or train, keep your phone active so our team can coordinate smoothly.",
      "",
      "Your latest booking, crew, and itinerary details are available here:",
      "{portal_url}",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      {
        name: "pickup_date",
        isRequired: true,
        description: "Pickup date",
        example: "15 Jan 2026",
      },
      {
        name: "pickup_time",
        isRequired: true,
        description: "Confirmed pickup time",
        example: "09:00",
      },
      {
        name: "pickup_location",
        isRequired: true,
        description: "Confirmed pickup place",
        example: "Surabaya Airport Terminal 2 arrival area",
      },
      {
        name: "dropoff_location",
        isRequired: true,
        description: "Confirmed final drop-off place",
        example: "Surabaya Airport",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO H-2 Trip Reminder",
    description: "48-hour reminder covering pickup, essentials, early starts, safety, support, and portal review.",
    content: [
      "*[JVTO] H-2 Trip Reminder*",
      "",
      "Hi {customer_name}, your *{package_name}* is coming soon.",
      "",
      "*Pickup*",
      "- Time: {pickup_time}",
      "- Location: {pickup_location}",
      "",
      "*Please prepare*",
      "- Warm jacket, hat, and gloves for Bromo/Ijen sunrise",
      "- Trekking shoes with good grip",
      "- Quick-dry clothes and waterproof bag for waterfall routes",
      "- Headlamp or flashlight for night trekking",
      "- Local cash in IDR for personal expenses and optional add-ons",
      "- Passport copy and medical check readiness if your itinerary includes Ijen",
      "",
      "Bromo and Ijen often start very early, around midnight to 2:00 AM depending on the route. Your portal has the latest itinerary, crew, payment, and preparation details:",
      "{portal_url}",
      "",
      "Reply here if you need help before departure.",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      packageName,
      {
        name: "pickup_time",
        isRequired: true,
        description: "Confirmed pickup time for the first tour day",
        example: "09:00",
      },
      {
        name: "pickup_location",
        isRequired: true,
        description: "Confirmed pickup place for the first tour day",
        example: "Surabaya Gubeng Train Station",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO Payment Clarity & Balance",
    description: "Explains total amount, paid amount, outstanding balance, due date, payment link, and portal ledger.",
    content: [
      "*[JVTO] Payment Clarity & Balance*",
      "",
      "Hi {customer_name}, here is the payment summary for your booking:",
      "",
      "- *Booking ID:* {booking_code}",
      "- *Tour package:* {package_name}",
      "- *Total amount:* {total_amount}",
      "- *Amount paid:* {amount_paid}",
      "- *Outstanding balance:* {outstanding_balance}",
      "- *Payment due date:* {payment_due_date}",
      "",
      "*Payment link*",
      "{payment_link}",
      "",
      "Your portal also shows the full payment history, invoices, inclusions, exclusions, and optional add-ons so there are no hidden costs:",
      "{portal_url}",
      "",
      "Please use only official JVTO links. We will never ask for your OTP or PIN.",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      {
        name: "booking_code",
        isRequired: true,
        description: "JVTO booking code",
        example: "JVTO-20260115-001",
      },
      packageName,
      {
        name: "total_amount",
        isRequired: true,
        description: "Formatted total booking amount with currency",
        example: "IDR 5,000,000",
      },
      {
        name: "amount_paid",
        isRequired: true,
        description: "Formatted amount already paid with currency",
        example: "IDR 2,000,000",
      },
      {
        name: "outstanding_balance",
        isRequired: true,
        description: "Formatted remaining balance with currency",
        example: "IDR 3,000,000",
      },
      {
        name: "payment_due_date",
        isRequired: true,
        description: "Final balance payment deadline",
        example: "12 Jan 2026",
      },
      {
        name: "payment_link",
        isRequired: true,
        description: "Official payment or invoice URL",
        example: "https://pay.javavolcano-touroperator.com/inv/abc123",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO Payment Received Confirmation",
    description: "Confirms successful payment and points the customer to invoices and payment history.",
    content: [
      "*[JVTO] Payment Received*",
      "",
      "Hi {customer_name}, we have received your payment.",
      "",
      "- *Booking ID:* {booking_code}",
      "- *Amount received:* {amount_received}",
      "- *Payment method:* {payment_method}",
      "- *Payment date:* {payment_date}",
      "",
      "Your booking payment history and invoice links are available in your customer portal:",
      "{portal_url}",
      "",
      "Thank you. We will continue preparing the operational details for your trip.",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      {
        name: "booking_code",
        isRequired: true,
        description: "JVTO booking code",
        example: "JVTO-20260115-001",
      },
      {
        name: "amount_received",
        isRequired: true,
        description: "Formatted received payment amount with currency",
        example: "IDR 3,000,000",
      },
      {
        name: "payment_method",
        isRequired: true,
        description: "Payment method used by the customer",
        example: "Wise",
      },
      {
        name: "payment_date",
        isRequired: true,
        description: "Date payment was received",
        example: "10 Jan 2026",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO Package Inclusions & Exclusions Reply",
    description: "Support reply for customers asking what is included, excluded, or whether there are hidden costs.",
    content: [
      "*[JVTO] Package Inclusions & Exclusions*",
      "",
      "Hi {customer_name}, for your *{package_name}*, the package generally includes:",
      "- Private AC transportation",
      "- Professional English-speaking guide",
      "- Accommodation with daily breakfast for multi-day tours",
      "- Entrance fees listed in your itinerary",
      "- 4x4 Jeep for the Bromo tour when included in the itinerary",
      "- Mineral water and selected meals shown in your package details",
      "",
      "Common exclusions are:",
      "- International/domestic flights",
      "- Personal travel insurance",
      "- Dinners and meals not listed as included",
      "- Tips for guide and driver",
      "- Optional add-ons such as Bromo horse ride when selected separately",
      "",
      "Your exact inclusions, exclusions, optional activities, and prices are shown in your portal:",
      "{portal_url}",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      packageName,
      portalUrl,
    ],
  },
  {
    name: "JVTO Daily Schedule Reply",
    description: "Support reply explaining daily schedule access, timing updates, meals, guide/driver info, and portal use.",
    content: [
      "*[JVTO] Daily Schedule Information*",
      "",
      "Hi {customer_name}, your schedule for *{day_label}* is available in your customer portal:",
      "{portal_url}",
      "",
      "The portal includes:",
      "- Activity timing and estimated travel time",
      "- What to expect during the day",
      "- Clothing and item tips for the route",
      "- Meal information for that day",
      "- Accommodation and crew details when available",
      "",
      "Some volcano activities start very early, especially Bromo sunrise and Ijen. Please follow the latest timing shown in the portal or sent by our operations team.",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      {
        name: "day_label",
        isRequired: true,
        description: "Trip day or activity label",
        example: "Day 2 - Mount Bromo Sunrise",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO Emergency & Support Reply",
    description: "Fast support reply for urgent help, emergency contact, email, and portal reference.",
    content: [
      "*[JVTO] Support & Emergency Contact*",
      "",
      "Hi {customer_name}, for urgent help during your trip, please contact JVTO through:",
      "",
      "- *WhatsApp:* {support_phone}",
      "- *Email:* {support_email}",
      "",
      "If your driver or guide details are already assigned, they are also listed in the Crew Details section of your portal:",
      "{portal_url}",
      "",
      "For urgent situations, WhatsApp is the fastest channel. Please share your location, booking name, and a short explanation of what happened.",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      {
        name: "support_phone",
        isRequired: true,
        description: "JVTO support WhatsApp number",
        example: "+62 822-4478-8833",
      },
      {
        name: "support_email",
        isRequired: true,
        description: "JVTO support email address",
        example: "javavolcanotouroperator@gmail.com",
      },
      portalUrl,
    ],
  },
  {
    name: "JVTO Change Request / Special Request Reply",
    description: "Support reply for dietary, trekking pole, T-shirt size, children, pickup edits, or booking change requests.",
    content: [
      "*[JVTO] Change / Special Request Received*",
      "",
      "Hi {customer_name}, we received your request about *{request_type}*.",
      "",
      "JVTO can review requests such as dietary restrictions, trekking poles, children traveling, T-shirt size, pickup details, early departures, or booking changes.",
      "",
      "Please make sure the latest information is also visible in your customer portal when the field is available:",
      "{portal_url}",
      "",
      "For booking changes or rescheduling, approval depends on availability and may involve a fee. Our team will confirm the operational impact before anything is finalized.",
      "",
      "- JVTO Team",
    ].join("\n"),
    mediaType: null,
    mediaUrl: null,
    mediaFilename: null,
    variables: [
      customerName,
      {
        name: "request_type",
        isRequired: true,
        description: "Type of change or special request",
        example: "vegetarian meal request",
      },
      portalUrl,
    ],
  },
];
